drop  database if exists minerlamp ;
create database minerlamp;
use  minerlamp;
create table user(id bigint primary key auto_increment,name varchar(20),pwd varchar(20),priv int );
create table staff(id bigint primary key auto_increment,name varchar(20),work_id bigint,sex int,birth_date varchar(10),certificate_no varchar(20),edu_level varchar(10),phone varchar(20), address varchar(50),rack_id bigint,lamp_no bigint,profession_id bigint, profession varchar(20),department_id bigint,department varchar(20),clazz_id bigint,clazz varchar(20),image blob,charging_lasttime datetime);
create table info_item(id bigint primary key auto_increment,name varchar(20),type int,value varchar(20));
create table lamp_unit(rack_id bigint,lamp_no bigint, name varchar(200), state int,charging_counts int, charging_begintime datetime,charging_lasttime datetime,manufacturer varchar(20),primary key(rack_id,lamp_no));
create table lamp_rack(id bigint primary key,name varchar(20));
create table led_setting(id bigint primary key,content varchar(200),display int);
create table lamp_change_log(id bigint auto_increment primary key,rack_id bigint,lamp_no bigint,work_id bigint,staff_name varchar(20),change_time datetime,operation int);
CREATE table charging_log(id BIGINT AUTO_INCREMENT PRIMARY KEY,work_id BIGINT,NAME VARCHAR(20),rack_id BIGINT,lamp_no BIGINT,profession VARCHAR(20),department VARCHAR(20),clazz_id BIGINT,clazz VARCHAR(20),underground_begintime DATETIME,underground_endtime DATETIME,old_state int,new_state int, action int,description VARCHAR(200),last_update_time timestamp default CURRENT_TIMESTAMP,clazz_day char(10)); 
create table rack_statistics(id bigint  primary key,idle_count bigint,charging_count bigint default 0,underground_count bigint default 0,error_count bigint default 0,full_count bigint default 0);
insert into user(name,pwd,priv) values("admin","admin",1);
insert into info_item(name,type,value) values( "教育程度",0,"高中");
insert into info_item(name,type,value) values( "教育程度",0,"专科");
insert into info_item(name,type,value) values( "教育程度",0,"本科");
insert into info_item(name,type,value) values( "工种",1,"工种1");
insert into info_item(name,type,value)  values( "工种",1,"工种2");
insert into info_item(name,type,value)  values( "工种",1,"工种3");
insert into info_item(name,type,value)  values( "部门",2,"部门1");
insert into info_item(name,type,value)  values( "部门",2,"部门2");
insert into info_item(name,type,value)  values( "部门",2,"部门3");
insert into info_item(name,type,value)  values( "班次",3,"8点");
insert into info_item(name,type,value)  values( "班次",3,"16点");
insert into info_item(name,type,value)  values( "班次",3,"0点");
